export type PlantMapping = {
    id: number
    symbol: string
    scientificName: string
    commonName?: Nullable<string>
    groupName?: Nullable<string>
    rankId: number
    rank: string
    acceptedId: number
    numImages?: Nullable<number>
    profileImageFilename?: Nullable<string>
    profileImageUrl?: Nullable<string>
    imageId?: Nullable<number>
    plantLocationId?: Nullable<number>
    durations?: Nullable<string>
    growthHabits?: Nullable<string>
    otherCommonNames?: Nullable<string>
    plantGuideUrls?: Nullable<string>
    factSheetUrls?: Nullable<string>
    distribution?: Nullable<DistributionMapping>
    characteristics?: Nullable<CharacteristicMapping>
}

export type DistributionMapping = {
    [key: string]: Nullable<string> | string[] | number | undefined
    plantId: number
    nativeStates?: string[]
    introducedStates?: string[]
    totalNativeStates?: Nullable<number>
    totalIntroducedStates?: Nullable<number>
}

export type CharacteristicMapping = {
    [key: string]: Nullable<string> | Nullable<number> | number | undefined
    plantId: number
    activeGrowthPeriod?: Nullable<string>
    bloat?: Nullable<string>
    cNRatio?: Nullable<string>
    coppicePotential?: Nullable<string>
    fallConspicuous?: Nullable<string>
    fireResistant?: Nullable<string>
    flowerColor?: Nullable<string>
    flowerConspicuous?: Nullable<string>
    foliageColor?: Nullable<string>
    foliagePorositySummer?: Nullable<string>
    foliagePorosityWinter?: Nullable<string>
    foliageTexture?: Nullable<string>
    fruitSeedColor?: Nullable<string>
    fruitSeedConspicuous?: Nullable<string>
    growthForm?: Nullable<string>
    growthRate?: Nullable<string>
    heightAt20YearsMaximumFeet?: Nullable<string>
    heightMatureFeet?: Nullable<string>
    knownAllelopath?: Nullable<string>
    leafRetention?: Nullable<string>
    lifespan?: Nullable<string>
    lowGrowingGrass?: Nullable<string>
    nitrogenFixation?: Nullable<string>
    resproutAbility?: Nullable<string>
    shapeAndOrientation?: Nullable<string>
    toxicity?: Nullable<string>
    adaptedToCoarseTexturedSoils?: Nullable<string>
    adaptedToFineTexturedSoils?: Nullable<string>
    adaptedToMediumTexturedSoils?: Nullable<string>
    anaerobicTolerance?: Nullable<string>
    caco3Tolerance?: Nullable<string>
    coldStratificationRequired?: Nullable<string>
    droughtTolerance?: Nullable<string>
    fertilityRequirement?: Nullable<string>
    fireTolerance?: Nullable<string>
    frostFreeDaysMinimum?: Nullable<string>
    hedgeTolerance?: Nullable<string>
    moistureUse?: Nullable<string>
    phMaximum?: Nullable<number>
    phMinimum?: Nullable<number>
    plantingDensityPerAcreMaximum?: Nullable<string>
    plantingDensityPerAcreMinimum?: Nullable<string>
    precipitationMaximum?: Nullable<string>
    precipitationMinimum?: Nullable<string>
    rootDepthMinimum?: Nullable<string>
    salinityTolerance?: Nullable<string>
    shadeTolerance?: Nullable<string>
    temperatureMinimumF?: Nullable<string>
    bloomPeriod?: Nullable<string>
    commercialAvailability?: Nullable<string>
    fruitSeedAbundance?: Nullable<string>
    fruitSeedPeriodBegin?: Nullable<string>
    fruitSeedPeriodEnd?: Nullable<string>
    fruitSeedPersistence?: Nullable<string>
    propagatedByBareRoot?: Nullable<string>
    propagatedByBulb?: Nullable<string>
    propagatedByContainer?: Nullable<string>
    propagatedByCorm?: Nullable<string>
    propagatedByCuttings?: Nullable<string>
    propagatedBySeed?: Nullable<string>
    propagatedBySod?: Nullable<string>
    propagatedBySprigs?: Nullable<string>
    propagatedByTubers?: Nullable<string>
    seedPerPound?: Nullable<string>
    seedSpreadRate?: Nullable<string>
    seedlingVigor?: Nullable<string>
    smallGrain?: Nullable<string>
    vegetativeSpreadRate?: Nullable<string>
    berryNutSeedProduct?: Nullable<string>
    christmasTreeProduct?: Nullable<string>
    fodderProduct?: Nullable<string>
    fuelwoodProduct?: Nullable<string>
    lumberProduct?: Nullable<string>
    navalStoreProduct?: Nullable<string>
    nurseryStockProduct?: Nullable<string>
    palatableBrowseAnimal?: Nullable<string>
    palatableHuman?: Nullable<string>
    postProduct?: Nullable<string>
    pulpwoodProduct?: Nullable<string>
    veneerProduct?: Nullable<string>
}

export type PlantTaxonomicPath = {
    plantId: number
    kingdom?: string
    phylum?: string
    className?: string
    orderName?: string
    family?: string
    genus?: string
    species?: string
    subspecies?: string
    variety?: string
    form?: string
    fullPath?: string
}

export const characteristicsKeys: Map<string, string> = new Map([
    ["activeGrowthPeriod", "active_growth_period"],
    ["bloat", "bloat"],
    ["cNRatio", "c_n_ratio"],
    ["coppicePotential", "coppice_potential"],
    ["fallConspicuous", "fall_conspicuous"],
    ["fireResistant", "fire_resistant"],
    ["flowerColor", "flower_color"],
    ["flowerConspicuous", "flower_conspicuous"],
    ["foliageColor", "foliage_color"],
    ["foliagePorositySummer", "foliage_porosity_summer"],
    ["foliagePorosityWinter", "foliage_porosity_winter"],
    ["foliageTexture", "foliage_texture"],
    ["fruitSeedColor", "fruit_seed_color"],
    ["fruitSeedConspicuous", "fruit_seed_conspicuous"],
    ["growthForm", "growth_form"],
    ["growthRate", "growth_rate"],
    ["heightAt20YearsMaximumFeet", "height_at_20_years_maximum_feet"],
    ["heightMatureFeet", "height_mature_feet"],
    ["knownAllelopath", "known_allelopath"],
    ["leafRetention", "leaf_retention"],
    ["lifespan", "lifespan"],
    ["lowGrowingGrass", "low_growing_grass"],
    ["nitrogenFixation", "nitrogen_fixation"],
    ["resproutAbility", "resprout_ability"],
    ["shapeAndOrientation", "shape_and_orientation"],
    ["toxicity", "toxicity"],
    ["adaptedToCoarseTexturedSoils", "adapted_to_coarse_textured_soils"],
    ["adaptedToFineTexturedSoils", "adapted_to_fine_textured_soils"],
    ["adaptedToMediumTexturedSoils", "adapted_to_medium_textured_soils"],
    ["anaerobicTolerance", "anaerobic_tolerance"],
    ["caco3Tolerance", "caco3_tolerance"],
    ["coldStratificationRequired", "cold_stratification_required"],
    ["droughtTolerance", "drought_tolerance"],
    ["fertilityRequirement", "fertility_requirement"],
    ["fireTolerance", "fire_tolerance"],
    ["frostFreeDaysMinimum", "frost_free_days_minimum"],
    ["hedgeTolerance", "hedge_tolerance"],
    ["moistureUse", "moisture_use"],
    ["phMaximum", "ph_maximum"],
    ["phMinimum", "ph_minimum"],
    ["plantingDensityPerAcreMaximum", "planting_density_per_acre_maximum"],
    ["plantingDensityPerAcreMinimum", "planting_density_per_acre_minimum"],
    ["precipitationMaximum", "precipitation_maximum"],
    ["precipitationMinimum", "precipitation_minimum"],
    ["rootDepthMinimum", "root_depth_minimum"],
    ["salinityTolerance", "salinity_tolerance"],
    ["shadeTolerance", "shade_tolerance"],
    ["temperatureMinimumF", "temperature_minimum_f"],
    ["bloomPeriod", "bloom_period"],
    ["commercialAvailability", "commercial_availability"],
    ["fruitSeedAbundance", "fruit_seed_abundance"],
    ["fruitSeedPeriodBegin", "fruit_seed_period_begin"],
    ["fruitSeedPeriodEnd", "fruit_seed_period_end"],
    ["fruitSeedPersistence", "fruit_seed_persistence"],
    ["propagatedByBareRoot", "propagated_by_bare_root"],
    ["propagatedByBulb", "propagated_by_bulb"],
    ["propagatedByContainer", "propagated_by_container"],
    ["propagatedByCorm", "propagated_by_corm"],
    ["propagatedByCuttings", "propagated_by_cuttings"],
    ["propagatedBySeed", "propagated_by_seed"],
    ["propagatedBySod", "propagated_by_sod"],
    ["propagatedBySprigs", "propagated_by_sprigs"],
    ["propagatedByTubers", "propagated_by_tubers"],
    ["seedPerPound", "seed_per_pound"],
    ["seedSpreadRate", "seed_spread_rate"],
    ["seedlingVigor", "seedling_vigor"],
    ["smallGrain", "small_grain"],
    ["vegetativeSpreadRate", "vegetative_spread_rate"],
    ["berryNutSeedProduct", "berry_nut_seed_product"],
    ["christmasTreeProduct", "christmas_tree_product"],
    ["fodderProduct", "fodder_product"],
    ["fuelwoodProduct", "fuelwood_product"],
    ["lumberProduct", "lumber_product"],
    ["navalStoreProduct", "naval_store_product"],
    ["nurseryStockProduct", "nursery_stock_product"],
    ["palatableBrowseAnimal", "palatable_browse_animal"],
    ["palatableHuman", "palatable_human"],
    ["postProduct", "post_product"],
    ["pulpwoodProduct", "pulpwood_product"],
    ["veneerProduct", "veneer_product"],
]);