export const STATES = [
    "Alabama".toUpperCase(),
    "Alaska".toUpperCase(),
    "Arizona".toUpperCase(),
    "Arkansas".toUpperCase(),
    "California".toUpperCase(),
    "Colorado".toUpperCase(),
    "Connecticut".toUpperCase(),
    "Delaware".toUpperCase(),
    "Florida".toUpperCase(),
    "Georgia".toUpperCase(),
    "Hawaii".toUpperCase(),
    "Idaho".toUpperCase(),
    "Illinois".toUpperCase(),
    "Indiana".toUpperCase(),
    "Iowa".toUpperCase(),
    "Kansas".toUpperCase(),
    "Kentucky".toUpperCase(),
    "Louisiana".toUpperCase(),
    "Maine".toUpperCase(),
    "Maryland".toUpperCase(),
    "Massachusetts".toUpperCase(),
    "Michigan".toUpperCase(),
    "Minnesota".toUpperCase(),
    "Mississippi".toUpperCase(),
    "Missouri".toUpperCase(),
    "Montana".toUpperCase(),
    "Nebraska".toUpperCase(),
    "Nevada".toUpperCase(),
    "New Hampshire".toUpperCase(),
    "New Jersey".toUpperCase(),
    "New Mexico".toUpperCase(),
    "New York".toUpperCase(),
    "North Carolina".toUpperCase(),
    "North Dakota".toUpperCase(),
    "Ohio".toUpperCase(),
    "Oklahoma".toUpperCase(),
    "Oregon".toUpperCase(),
    "Pennsylvania".toUpperCase(),
    "Rhode Island".toUpperCase(),
    "South Carolina".toUpperCase(),
    "South Dakota".toUpperCase(),
    "Tennessee".toUpperCase(),
    "Texas".toUpperCase(),
    "Utah".toUpperCase(),
    "Vermont".toUpperCase(),
    "Virginia".toUpperCase(),
    "Washington".toUpperCase(),
    "West Virginia".toUpperCase(),
    "Wisconsin".toUpperCase(),
    "Wyoming".toUpperCase(),
    "American Samoa".toUpperCase(),
    "Federated States of Micronesia".toUpperCase(),
    "Guam".toUpperCase(),
    "Marshall Islands".toUpperCase(),
    "Northern Mariana Islands".toUpperCase(),
    "Palau".toUpperCase(),
    "Puerto Rico".toUpperCase(),
    "U.S. Minor Outlying Islands".toUpperCase(),
    "Virgin Islands".toUpperCase(),
    "Alberta".toUpperCase(),
    "British Columbia".toUpperCase(),
    "Manitoba".toUpperCase(),
    "New Brunswick".toUpperCase(),
    "Nova Scotia".toUpperCase(),
    "Ontario".toUpperCase(),
    "Prince Edward Island".toUpperCase(),
    "Quebec".toUpperCase(),
    "Saskatchewan".toUpperCase(),
    "Yukon".toUpperCase(),
    "Northwest Territories".toUpperCase(),
    "Nunavut".toUpperCase(),
    "Labrador".toUpperCase(),
    "Newfoundland".toUpperCase(),
    "Greenland".toUpperCase(),
    "Saint Pierre and Miquelon".toUpperCase(),
    "Navassa Island".toUpperCase(),
]